name: snakemake-tutorial
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - graphviz=2.40.1
  - networkx=2.4
  - pandas=1.0.1
  - pygraphviz=1.3
  - python=3.7.6
  - r-base=3.6.1
  - r-essentials=3.6
  - snakemake-minimal=5.10.0
  - xsv=0.13.0

