name: snakemake-tutorial
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - pandas=1.0.1
  - python=3.7.6
  - r-base=3.6.1
  - r-essentials=3.6
  - snakemake-minimal=5.10.0
  - xsv=0.13.0=0

